flat_deuxieme_flat.Rmd:
  path: dev/flat_deuxieme_flat.Rmd
  state: active
  R:
  - R/deuxieme_flat.R
  - R/fonction2.R
  tests:
  - tests/testthat/test-deuxieme_flat.R
  - tests/testthat/test-fonction2.R
  vignettes: vignettes/go-further.Rmd
  inflate:
    flat_file: dev/flat_deuxieme_flat.Rmd
    vignette_name: Go further
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R: R/first.R
  tests: tests/testthat/test-first.R
  vignettes: vignettes/minimal.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: Minimal
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_tirage_loto.Rmd:
  path: dev/flat_tirage_loto.Rmd
  state: active
  R: R/tirage_loto.R
  tests: tests/testthat/test-tirage_loto.R
  vignettes: vignettes/go-further.Rmd
  inflate:
    flat_file: dev/flat_tirage_loto.Rmd
    vignette_name: Go further
    open_vignette: true
    check: true
    document: true
    overwrite: ask
