# WARNING - Generated by {fusen} from dev/flat_tirage_loto.Rmd: do not edit by hand

#' tirage du loto
#' @return un vecteur avec 6 numéros + 2 numéros complémentaires
#' @export
#' @examples
#' tirage_loto()
tirage_loto <- function() {
  six_numeros <- sample(1:49, size = 6, replace = FALSE)
  numeros_complementaires <- tirage_numeros_complementaires()
  tirage_complet <- c(six_numeros, numeros_complementaires)
  return(tirage_complet)
}

tirage_numeros_complementaires <- function() {
  numeros_complementaires <- sample(1:9, size = 2, replace = FALSE)
  return(numeros_complementaires)
}
